export const SALES_INTENTS = {
  GENERAL_QUESTION: 'GENERAL_QUESTION',
  PRODUCT_INQUIRY: 'PRODUCT_INQUIRY',
  REQUIREMENTS_DISCOVERY: 'REQUIREMENTS_DISCOVERY',
  PRICING_INQUIRY: 'PRICING_INQUIRY',
  PRICE_NEGOTIATION: 'PRICE_NEGOTIATION',
  COMPETITOR_COMPARISON: 'COMPETITOR_COMPARISON',
  OBJECTION: 'OBJECTION',
  DEMO_REQUEST: 'DEMO_REQUEST',
  PURCHASE_INTENT: 'PURCHASE_INTENT',
  FOLLOW_UP: 'FOLLOW_UP',
  HUMAN_ESCALATION: 'HUMAN_ESCALATION',
};

export const RECOMMENDED_ACTIONS = {
  ASK_REQUIREMENT: 'ASK_REQUIREMENT',
  ANSWER_PRODUCT_QUESTION: 'ANSWER_PRODUCT_QUESTION',
  PRESENT_PRICING: 'PRESENT_PRICING',
  ADDRESS_OBJECTION: 'ADDRESS_OBJECTION',
  COMPARE_COMPETITOR: 'COMPARE_COMPETITOR',
  OFFER_APPROVED_CONCESSION: 'OFFER_APPROVED_CONCESSION',
  REQUEST_MANAGER_APPROVAL: 'REQUEST_MANAGER_APPROVAL',
  BOOK_DEMO: 'BOOK_DEMO',
  FOLLOW_UP: 'FOLLOW_UP',
  ESCALATE_HUMAN: 'ESCALATE_HUMAN',
};

export const SALES_STRATEGIES = {
  VALUE_DEFENSE: 'VALUE_DEFENSE',
  COMPETITIVE_DIFFERENTIATION: 'COMPETITIVE_DIFFERENTIATION',
  COMMERCIAL_CONCESSION: 'COMMERCIAL_CONCESSION',
  DISCOVERY_EXPANSION: 'DISCOVERY_EXPANSION',
  CLOSING_ACCELERATION: 'CLOSING_ACCELERATION',
  HUMAN_HANDOFF: 'HUMAN_HANDOFF',
};

export const INTENT_LIST = Object.values(SALES_INTENTS);
export const ACTION_LIST = Object.values(RECOMMENDED_ACTIONS);
export const STRATEGY_LIST = Object.values(SALES_STRATEGIES);
