export const DEAL_STAGES = {
  NEW: 'NEW',
  QUALIFICATION: 'QUALIFICATION',
  DISCOVERY: 'DISCOVERY',
  EVALUATION: 'EVALUATION',
  NEGOTIATION: 'NEGOTIATION',
  DEMO_REQUESTED: 'DEMO_REQUESTED',
  CLOSED_WON: 'CLOSED_WON',
  CLOSED_LOST: 'CLOSED_LOST',
};

export const BUYING_INTENT = {
  UNKNOWN: 'UNKNOWN',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  VERY_HIGH: 'VERY_HIGH',
};

export const OBJECTION_TYPES = {
  PRICE: 'PRICE',
  BUDGET: 'BUDGET',
  COMPETITOR: 'COMPETITOR',
  TRUST_SECURITY: 'TRUST_SECURITY',
  FEATURE: 'FEATURE',
  TIMING: 'TIMING',
  AUTHORITY: 'AUTHORITY',
  OTHER: 'OTHER',
};

export const OBJECTION_STATUS = {
  UNRESOLVED: 'UNRESOLVED',
  ADDRESSED: 'ADDRESSED',
  RESOLVED: 'RESOLVED',
};

export const STAGE_LIST = Object.values(DEAL_STAGES);
export const BUYING_INTENT_LIST = Object.values(BUYING_INTENT);
export const OBJECTION_TYPE_LIST = Object.values(OBJECTION_TYPES);
export const OBJECTION_STATUS_LIST = Object.values(OBJECTION_STATUS);
