export const BILLING_CYCLES = {
  MONTHLY: 'MONTHLY',
  SIX_MONTH: 'SIX_MONTH',
  ANNUAL: 'ANNUAL',
  MULTI_YEAR: 'MULTI_YEAR',
};

export const POLICY_STATUS = {
  APPROVED: 'APPROVED',
  REQUIRES_APPROVAL: 'REQUIRES_APPROVAL',
  REJECTED: 'REJECTED',
};

export const PRICING_TIERS = {
  STARTER: {
    tier: 'STARTER',
    name: 'Starter',
    description: 'Essential AI sales automation for small sales teams.',
    priceAmount: 100,
    pricePeriod: 'month',
    sixMonthAmount: 600,
    pricePerUserMonthly: 100,
    pricePerUserAnnual: null,
    minimumUsers: 1,
    maximumUsers: 20,
    allowedBillingCycles: ['MONTHLY', 'SIX_MONTH'],
    maximumDiscountPct: 0,
    volumeDiscountRules: [],
    features: ['AI Sales Agent', 'Real-time conversational voice AI', 'Lead management', 'Conversation history', 'Basic deal tracking', 'Follow-up management'],
  },
  PROFESSIONAL: {
    tier: 'PROFESSIONAL',
    name: 'Professional',
    description: 'Advanced AI conversations and pipeline intelligence for growing teams.',
    priceAmount: 200,
    pricePeriod: 'month',
    sixMonthAmount: 1200,
    pricePerUserMonthly: 200,
    pricePerUserAnnual: null,
    minimumUsers: 1,
    maximumUsers: 100,
    allowedBillingCycles: ['MONTHLY', 'SIX_MONTH'],
    maximumDiscountPct: 0,
    volumeDiscountRules: [],
    features: ['Everything in Starter', 'Advanced AI sales conversations', 'Customer qualification', 'Objection handling', 'Buying Intent / Deal State', 'Competitive Price Comparator', 'Sales pipeline analytics', 'Human Handoff'],
  },
  ENTERPRISE: {
    tier: 'ENTERPRISE',
    name: 'Enterprise',
    description: 'Full sales intelligence, administration, and access control.',
    priceAmount: 500,
    pricePeriod: 'month',
    sixMonthAmount: 3000,
    pricePerUserMonthly: 500,
    pricePerUserAnnual: null,
    minimumUsers: 20,
    maximumUsers: 10000,
    allowedBillingCycles: ['MONTHLY', 'SIX_MONTH'],
    maximumDiscountPct: 0,
    volumeDiscountRules: [],
    features: ['Everything in Professional', 'Advanced sales intelligence', 'Advanced deal management', 'Full conversation analytics', 'Advanced buying-intent insights', 'Intelligent Human Handoff', 'Company and user administration', 'Role-based access control'],
  },
  GROWTH: {
    tier: 'GROWTH',
    name: 'Growth',
    description: 'Annual plan for teams ready to scale their sales operation.',
    priceAmount: 5000,
    pricePeriod: 'year',
    sixMonthAmount: null,
    pricePerUserMonthly: null,
    pricePerUserAnnual: 5000,
    minimumUsers: 1,
    maximumUsers: 10000,
    allowedBillingCycles: ['ANNUAL'],
    maximumDiscountPct: 15,
    volumeDiscountRules: [],
    features: ['AI Sales Agent', 'Real-time voice conversations', 'Lead management', 'Conversation history', 'Deal tracking', 'Buying Intent / Deal State', 'Follow-ups', 'Price Comparator', 'Human Handoff'],
  },
  ENTERPRISE_ANNUAL: {
    tier: 'ENTERPRISE_ANNUAL',
    name: 'Enterprise Annual',
    description: 'Annual enterprise sales management for complex organizations.',
    priceAmount: 10000,
    pricePeriod: 'year',
    sixMonthAmount: null,
    pricePerUserMonthly: null,
    pricePerUserAnnual: 10000,
    minimumUsers: 1,
    maximumUsers: 10000,
    allowedBillingCycles: ['ANNUAL'],
    maximumDiscountPct: 25,
    volumeDiscountRules: [],
    features: ['Everything in Growth', 'Advanced sales intelligence', 'Advanced pipeline management', 'Full conversation analytics', 'Advanced buying-intent analysis', 'Intelligent Human Handoff', 'Company and user administration', 'Role-based access control', 'Enterprise-level sales management'],
  },
};

export const SUPPORTED_TIERS = Object.keys(PRICING_TIERS);
export const SUPPORTED_BILLING_CYCLES = Object.values(BILLING_CYCLES);
